<template>
  <div>
    <h1>Todo List</h1>
    <ul>
      <ListItem v-for="item in items" :key="item.id" :item="item" />
    </ul>
  </div>
</template>

<script>
/* this page is generated by copilot */
import ListItem from './ListItem.vue';

export default {
  name: 'TodoList',
  components: {
    ListItem
  },
  data() {
    return {
      items: [
        { id: 1, text: 'Task 1', completed: false },
        { id: 2, text: 'Task 2', completed: true },
        { id: 3, text: 'Task 3', completed: false }
      ]
    };
  }
};
</script>

<style scoped>
/* Add your custom styles here */
</style>
