<template>
    <div class="todo-main">
        <ListItem v-for="item in todo.items" :item="item"/>
    </div>
</template>

<script setup>
/* this page is generated by copilot */
import ListItem from './ListItem.vue';
import { useItemStore } from '@/stores/ItemStore';

const todo = useItemStore();
</script>

<style scoped>
.todo-main {
    margin-left: 0px;
    padding: 1px;
}
</style>
